### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by jacklul** [lucacome/docker-image-update-checker#2]
This action doesn't seem to work properly in my use case...
It runs without error but for [this configuration](https://github.com/jacklul/pihole-updatelists/blob/master/.github/workflows/image-latest.yml) it does not set **needs-updating** to **true** when the base image was updated, any idea why would that be?

**Comment by lucacome** [comment]
@jacklul you can't access the output directly if the action it's in a different job, you would need to set the output of the job, something like:
```
jobs:
  check:
    runs-on: ubuntu-latest
	outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: pihole/pihole:latest
          image: jacklul/pihole:latest
        if: ${{ github.event_name == 'schedule' }}

  build:
    needs: check
    if: ${{ github.event_name != 'schedule' || needs.check.outputs.image-needs-updating == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

```
