### ISSUE TITLE
Fails on platforms with variants

### ISSUE THREAD

**Issue by zinen** [lucacome/docker-image-update-checker#27]
I tried a lot of stuff that ended with an `UNAUTHORIZED` response from the docker API.

Some troubleshooting let me to that this error is gone if I remove the platforms with variants. E.g. removing `linux/arm/v6` and `linux/arm/v7` from the platforms input.

My code that fails:

```yaml
jobs:
  get-docker-version:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: alpine:latest
          image: zinen2/alpine-pigpiod:latest
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64
          # platforms: linux/arm64
        env:
          DEBUG: true
```
