### ISSUE TITLE
Support any container registry

### ISSUE THREAD

**Issue by mkumatag** [lucacome/docker-image-update-checker#4]
Rightnow code is more tied with docker hub but there are other registries like quay, gcr, wondering if we can enhance the code to support all the remaining registries.

**Comment by twiddler** [comment]
I'm interested in using this action with private images on ghcr. Subscribed! :partying_face:

**Comment by mkumatag** [comment]
@twiddler I have just tried implementing the missing feature here - https://github.com/mkumatag/container-image-updater-action, can see if that works for you?

**Comment by twiddler** [comment]
@mkumatag Well that was fast. :open_mouth: I checked your project but I didn't see how to provide the registry where to look up the file.

Thinking about it, I saw you use https://github.com/estesp/manifest-tool. (Or at least that's what I got from the code, although I honestly haven't written any Go yet.) They say 

> Note: For pushing to an authenticated registry like DockerHub, you will need a config generated via docker login

which reminded me there is https://github.com/docker/login-action that probably quite a few people already use. I honestly do not know how, but I think it'd be elegant to leverage that action. I'd assume that in most scenarios the base image to compare to is public anyway, or at least the base image and the one that builds on it are in the same private container registry. That would allow to write something along the lines of

```yml
- uses: docker/login-action@v1
  with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

- uses: someone/docker-image-update-checker@v1
  with:
      base-image: library/alpine:latest
      my-image: ghcr.io/me/my-private-image
```

What do you think? :thinking:

**Comment by mkumatag** [comment]
> @mkumatag Well that was fast. 😮 I checked your project but I didn't see how to provide the registry where to look up the file. My images are in a private ghcr repository, not at Docker Hub.
> 
> Thinking about it, I saw you use https://github.com/estesp/manifest-tool. (Or at least that's what I got from the code, although I honestly haven't written any Go yet.) They say
> 
> > Note: For pushing to an authenticated registry like DockerHub, you will need a config generated via docker login
> 
> which reminded me there is https://github.com/docker/login-action that probably quite a few people already use. I honestly do not know how, but I think it'd be elegant to leverage that action. I'd assume that in most scenarios the base image to compare to is public anyway, or at least the base image and the one that builds on it are in the same private container registry. That would allow to write something along the lines of
> 
> ```yaml
> - uses: docker/login-action@v1
>   with:
>       registry: ghcr.io
>       username: ${{ github.actor }}
>       password: ${{ secrets.GITHUB_TOKEN }}
> 
> - uses: someone/docker-image-update-checker@v1
>   with:
>       base-image: library/alpine:latest
>       my-image: ghcr.io/me/my-private-image
> ```
> 
> What do you think? 🤔

can we discuss the in the same repo for others benefit?

**Comment by twiddler** [comment]
I saw your custom action is a docker image. Holy moly, I didn't know that was possible! :open_mouth: That lets us use `skopeo` which has a _really_ simple API for inspecting images, see https://github.com/containers/skopeo. I think it makes a lot of sense to re-use that project. Actually I couldn't help but to get started with it. If you like to, check my progress at https://github.com/twiddler/is-my-docker-parent-image-out-of-date. :partying_face: No login so far though, but I _think_ that should be easy with `skopeo`.

**Comment by mkumatag** [comment]
> I saw your custom action is a docker image. Holy moly, I didn't know that was possible! 😮 That lets us use `skopeo` which has a _really_ simple API for inspecting images, see https://github.com/containers/skopeo. I think it makes a lot of sense to re-use that project. Actually I couldn't help but to get started with it. If you like to, check my progress at https://github.com/twiddler/is-my-docker-parent-image-out-of-date. 🥳 No login so far though, but I _think_ that should be easy with `skopeo`.

of course you can use, but didn't wanted to invest lot of time on this and just wanted something real quick so I used what I used before :)

and wrt to auth, yon use something like below and works:

```yaml
- uses: docker/login-action@v1
  with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

- uses: mkumatag/container-image-updater-action@v1.0.5
  with:
    base-image: 'library/alpine:latest'
    image: 'ghcr.io/me/my-private-image'
    image-reg-username: ${{ github.actor }}
    image-reg-password: ${{ secrets.GITHUB_TOKEN }}
```
