### ISSUE TITLE
Feature suggestion: Multiplatform builds for the same tag

### ISSUE THREAD

**Issue by hbontempo-br** [lucacome/docker-image-update-checker#9]
First of all: great action! Thank you for your work.

It's possible to have different builds for deferent platforms under the under the same tag.
This actions should be able to point if any of the platform image needs update.

Maybe even explicitly ask what platforms should be validated
```yaml
    steps:
      - 
        name: Docker Image Update Checker
        id: base_update_check
        uses: lucacome/docker-image-update-checker@v1.1.1
        with:
          base-image: a-tag
          image: another_tag
          platforms: linux/amd64,linux/arm64

```
